"""refactor code

Revision ID: 2c24e9082202
Revises: 63b5254a8c20
Create Date: 2024-02-17 18:11:18.857753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c24e9082202'
down_revision: Union[str, None] = '63b5254a8c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'teachers', ['teacher_id'], ['teacher_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'teacher_id')
    # ### end Alembic commands ###
