"""delete unique in teacher_id

Revision ID: 3fc95d4bf21d
Revises: eb9d5877535a
Create Date: 2024-02-17 01:25:20.082580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fc95d4bf21d"
down_revision: Union[str, None] = "eb9d5877535a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("classes_teacher_id_key", "classes", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("classes_teacher_id_key", "classes", ["teacher_id"])
    # ### end Alembic commands ###
