"""add to Grade - value

Revision ID: 6349d9e78d1b
Revises: c342ec2bb7c7
Create Date: 2024-02-17 01:37:07.079744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6349d9e78d1b"
down_revision: Union[str, None] = "c342ec2bb7c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grades", sa.Column("value", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grades", "value")
    # ### end Alembic commands ###
