"""delete userlist in lesson

Revision ID: 63b5254a8c20
Revises: e3bfed7c099c
Create Date: 2024-02-17 01:48:53.511194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63b5254a8c20"
down_revision: Union[str, None] = "e3bfed7c099c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
